#!/bin/bash
###############################################################################
# Quick Reference: Zero-Day Detection Framework PoC Operations
###############################################################################

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_section() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n"
}

print_section "CLUSTER MANAGEMENT"
echo "Start Minikube:"
echo "  minikube start --cpus=2 --memory=3072 --disk-size=20g"
echo ""
echo "Stop Minikube:"
echo "  minikube stop"
echo ""
echo "Check Cluster Status:"
echo "  kubectl cluster-info"
echo "  kubectl get nodes"

print_section "VIEW DEPLOYMENTS"
echo "List all pods across namespaces:"
echo "  kubectl get pods -A"
echo ""
echo "Watch specific namespace:"
echo "  kubectl get pods -n ml -w"
echo ""
echo "Detailed pod info:"
echo "  kubectl describe pod <pod-name> -n <namespace>"

print_section "INFERENCE SERVICE"
echo "Forward inference service port:"
echo "  kubectl -n ml port-forward svc/inference 8080:8080 &"
echo ""
echo "Test scoring endpoint:"
echo "  curl -X POST http://localhost:8080/score \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"features\": [0.1, 0.2, ..., 1.6]}'"
echo ""
echo "Test health endpoint:"
echo "  curl http://localhost:8080/health"
echo ""
echo "View inference service logs:"
echo "  kubectl logs -n ml deployment/inference-service --tail=50 -f"

print_section "GRAPH-BUILDER"
echo "View graph-builder logs:"
echo "  kubectl logs -n ml deployment/graph-builder --tail=50 -f"
echo ""
echo "Check generated windows:"
echo "  kubectl exec -n ml <graph-builder-pod> -- ls -la /data/graphs"
echo ""
echo "Inspect a Parquet window file:"
echo "  kubectl exec -n ml <graph-builder-pod> -- python3 -c \\"
echo "    'import pyarrow.parquet as pq; print(pq.read_table(\"/data/graphs/window_*.parquet\").to_pandas())'"

print_section "CONTAINMENT OPERATOR"
echo "List containment resources:"
echo "  kubectl get containments -n quarantine"
echo ""
echo "Create dry-run containment:"
echo "  kubectl apply -f - << 'EOF'"
echo "apiVersion: security.example.com/v1alpha1"
echo "kind: Containment"
echo "metadata:"
echo "  name: test-containment"
echo "  namespace: quarantine"
echo "spec:"
echo "  alertID: \"alert-test\""
echo "  confidence: 0.8"
echo "  suggestedAction: \"isolate_pod\""
echo "  dryRun: true"
echo "EOF"
echo ""
echo "View containment status:"
echo "  kubectl describe containment <name> -n quarantine"
echo ""
echo "View operator logs:"
echo "  kubectl logs -n quarantine deployment/containment-operator -f"

print_section "KAFKA CLUSTER"
echo "Check Kafka status:"
echo "  kubectl get kafka -n kafka -o wide"
echo ""
echo "Fix Kafka version (if NotReady):"
echo "  sed -i 's/version: \"3.3.1\"/version: \"4.0.0\"/' infra/k8s/kafka/kafka-cluster.yaml"
echo "  kubectl apply -f infra/k8s/kafka/kafka-cluster.yaml"
echo ""
echo "Watch Kafka cluster startup:"
echo "  kubectl get kafka my-cluster -n kafka -w"

print_section "MONITORING & TELEMETRY"
echo "View OTel Collector logs:"
echo "  kubectl logs -n monitoring deployment/otel-collector -f"
echo ""
echo "Check monitoring stack:"
echo "  kubectl get pods -n monitoring"

print_section "DEPLOYMENT & VALIDATION"
echo "Run quick deployment:"
echo "  bash scripts/quick-deploy.sh"
echo ""
echo "Run full validation suite:"
echo "  bash scripts/validate-poc.sh"
echo ""
echo "Build containment operator image:"
echo "  docker build -t containment-operator:latest containment/"
echo "  minikube image load containment-operator:latest"

print_section "BUILD IMAGES"
echo "Build graph-builder image:"
echo "  docker build -t graph-builder:latest graph_builder/"
echo "  minikube image load graph-builder:latest"
echo ""
echo "Build inference image:"
echo "  docker build -t inference:latest ml/ -f ml/Dockerfile.inference"
echo "  minikube image load inference:latest"
echo ""
echo "Build ML trainer image (requires torch):"
echo "  docker build -t ml:latest ml/"
echo "  minikube image load ml:latest"

print_section "DEBUGGING"
echo "SSH into Minikube VM:"
echo "  minikube ssh"
echo ""
echo "Run shell in pod:"
echo "  kubectl exec -it -n <ns> <pod> -- /bin/bash"
echo ""
echo "Port-forward to service:"
echo "  kubectl -n <ns> port-forward svc/<service> <local>:<remote> &"
echo ""
echo "Get pod events:"
echo "  kubectl describe pod <pod> -n <ns> | grep -A 20 Events:"
echo ""
echo "Check PVC status:"
echo "  kubectl get pvc -A"
echo ""
echo "Inspect Kubernetes resources:"
echo "  kubectl get all -n <namespace>"
echo "  kubectl get crd | grep security"

print_section "CLEANUP"
echo "Delete all resources in namespace:"
echo "  kubectl delete ns <namespace>"
echo ""
echo "Delete Minikube cluster:"
echo "  minikube delete"
echo ""
echo "Clean Docker images:"
echo "  docker image prune -a"

print_section "USEFUL LINKS & RESOURCES"
echo "- Kubernetes Documentation: https://kubernetes.io/docs/"
echo "- Minikube: https://minikube.sigs.k8s.io/"
echo "- Strimzi Kafka Operator: https://strimzi.io/"
echo "- Controller Runtime (Operator Development): https://github.com/kubernetes-sigs/controller-runtime"
echo "- Deployment Report: see DEPLOYMENT_REPORT.md"
echo "- Project Documentation: see README.md"

echo ""
echo -e "${GREEN}✓ Quick reference generated. For more details, see DEPLOYMENT_REPORT.md${NC}"
echo ""
