apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: containments.security.example.com
spec:
  group: security.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                alertID:
                  type: string
                confidence:
                  type: number
                suggestedAction:
                  type: string
                dryRun:
                  type: boolean
            status:
              type: object
  scope: Namespaced
  names:
    plural: containments
    singular: containment
    kind: Containment
    shortNames:
      - cnt
